spring.application.name=tgdd-api

# MongoDB Configuration Spring Boot 4.0
spring.mongodb.uri=mongodb://localhost:27017/tgdd
spring.mongodb.database=tgdd
spring.mongodb.host=localhost
spring.mongodb.port=27017

# Server Port
server.port=8080

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.core.convert=TRACE
logging.level.org.mongodb.driver=WARN
logging.file.name=spring.log

# JWT
jwt.secret=tgdd-super-secret-key-at-least-256-bits-long-for-hs256-algorithm-2024
jwt.expiration-ms=86400000
