import mongoose, { Schema } from 'mongoose';

const CellPhoneModelBrandSchema: Schema = new Schema({
  Network: { type: String },
  Primary_camera: { type: String },
  Chipset: { type: String },
  Announced: { type: String },
  Bluetooth: { type: String },
  EDGE: { type: String },
  Battery: { type: String },
  CPU: { type: String },
  USB: { type: String },
  RAM: { type: String },
  Network_Speed: { type: String },
  Memory_card: { type: String },
  Dimensions: { type: String },
  SIM: { type: String },
  NFC: { type: String },
  Colors: { type: String },
  Display_type: { type: String },
  Brand: { type: String },
  Sensors: { type: String },
  TwoG: { type: String },
  Loud_speaker: { type: String },
  GPRS: { type: String },
  Internal_memory: { type: String },
  field13: { type: String },
  WLAN: { type: String },
  Radio: { type: String },
  Status: { type: String },
  Model: { type: String },
  Display_size: { type: String },
  GPU: { type: String },
  Secondary_camera: { type: String },
  ThreeG: { type: String },
  Audio_jack: { type: String },
  Display_resolution: { type: String },
  Operating_System: { type: String },
  FourG: { type: String },
  GPS: { type: String },
  field38: { type: String },
  Weight: { type: String },
  price: { type: Number },
  images: [{ type: String }],
  embedding: { type: [Number], index: true },
  Cell_Phone_Brands: [{ type: Schema.Types.ObjectId, ref: 'CellPhoneModelBrand' }],
  Cell_Phone_Models: [{ type: Schema.Types.ObjectId, ref: 'CellPhoneModelBrand' }],
  ACL: { type: Object },
}, {
  timestamps: true,
  collection: 'Dataset_Cell_Phones_Model_Brand'
});

export default mongoose.model('CellPhoneModelBrand', CellPhoneModelBrandSchema);
